repositories:
  - prefix: bitnami
    urls:
      - https://charts.bitnami.com/bitnami
  - prefix: jetstack
    urls:
      - https://charts.jetstack.io
  - prefix: jenkins-x
    urls:
      - https://jenkins-x-charts.github.io/v2
  - prefix: stable
    urls:
      - https://charts.helm.sh/stable
  - prefix: flagger
    urls:
      - https://flagger.app
  - prefix: gloo
    urls:
      - https://storage.googleapis.com/solo-public-helm
  - prefix: vmware-tanzu
    urls:
      - https://vmware-tanzu.github.io/helm-charts
